language: python

python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8

env:
  global:
    - CC_TEST_REPORTER_ID=fde8ee1407f0a9d2c1ecf30dc37fa718feb2381526d89b2c9d8c0cb6fba6e2ad

install:
  - pip install -r requirements.txt

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: make test PYTEST_EXTRA_ARGS="--cov=metastore"

after_script:
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache:
  directories:
    - $HOME/.cache/pip
